### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by naraesk** [softvis-research/jqa-javasrc-plugin#2]
How can I use this plugin via maven without compiling it myself? I haven't found any version on https://mvnrepository.com/. When using the default jqassistant-maven-plugin 1.6.0 the javasrc-plugin is not loaded as far as I can tell.

**Comment by rmllr** [comment]
That's correct. As this plugin is not officially released yet, it is not available at https://mvnrepository.com/. Currently, you have to compile it yourself.

**Comment by naraesk** [comment]
And how do I compile the plugin? I used `mvn install` on the master branch but it didn't work. See log for details.
[maven.log](https://github.com/softvis-research/jqa-javasrc-plugin/files/3128813/maven.log)

**Comment by rmllr** [comment]
I have change the version of the parent pom to 1.5.0 (c61c29c157a6ee6540e94848e4286303d4900e12). Now it compiles successfully.
